# Generated by Django 4.2.7 on 2025-09-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='AI Developer', max_length=100)),
                ('role', models.CharField(default='Machine Learning Engineer', max_length=100)),
                ('bio', models.TextField(default='Passionate AI developer building intelligent solutions')),
                ('avatar', models.ImageField(blank=True, upload_to='profile/')),
                ('location', models.CharField(default='Silicon Valley', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to='documents/')),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('ai_ml', 'AI/ML'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('tools', 'Tools'), ('cloud', 'Cloud')], max_length=50)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
